allprojects {
    ext.kotlin_version = '1.8.0'
    repositories {
        google()
        mavenCentral()
        maven { url "https://maven.aliyun.com/repository/public" } // Alternative repository
        maven { url "https://developer.huawei.com/repo/" } // Huawei repository
        maven { url "https://jitpack.io" } // JitPack for missing dependencies
    }
}


rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
